### PR TITLE
Fix crash in http.py on Python 3.9

### PR DESCRIPTION
**Pull request by siebert**

### CODE REVIEW

**Comment by siebert** [comment]
@malmeloo How can I trigger the checks for the pull request?

**Review by malmeloo — CHANGES_REQUESTED** [review]
I think this section could be improved by making the first `.get` a `.pop` and specifying `None` as a default value, then the `else` could be avoided altogether

**Comment by malmeloo** [comment]
> @malmeloo How can I trigger the checks for the pull request?

I think I need to manually approve them to run, but I can't figure it out on mobile :-). But don't worry about it, there's no test coverage for this anyway. If you can make the changes I proposed I'll go ahead and merge it.

**Review by malmeloo — APPROVED** [review]
Nice thank you, will merge it soon 👍

**Pull request merged**
